"""quiz_data.py — practice question bank for the NISM Quiz tab.

IMPORTANT: these are original PRACTICE questions written to reinforce core
derivatives and research-analyst concepts. They are NOT reproductions of the
official NISM Series-XV (or any) exam. Extend QUESTIONS freely.

Each item: {"q", "options" (list), "answer" (0-based index), "topic", "exp"}.
"""

QUESTIONS = [
    {"q": "The delta of an at-the-money (ATM) call option is approximately:",
     "options": ["0", "0.5", "1.0", "-0.5"], "answer": 1, "topic": "Greeks",
     "exp": "An ATM call has delta near 0.5; it rises toward 1 as it goes ITM."},
    {"q": "Which Greek measures the rate of change of delta with respect to the "
          "underlying price?",
     "options": ["Theta", "Vega", "Gamma", "Rho"], "answer": 2, "topic": "Greeks",
     "exp": "Gamma is the second derivative of option value w.r.t. spot."},
    {"q": "For a long option position, theta is generally:",
     "options": ["Positive", "Negative", "Zero", "Undefined"], "answer": 1,
     "topic": "Greeks", "exp": "Long options lose time value as expiry nears, "
     "so theta is negative."},
    {"q": "Vega measures an option's sensitivity to changes in:",
     "options": ["Interest rates", "Time", "Implied volatility", "Dividends"],
     "answer": 2, "topic": "Greeks",
     "exp": "Vega is the change in option price per 1% change in volatility."},
    {"q": "Gamma is typically highest for options that are:",
     "options": ["Deep ITM, far from expiry", "ATM, near expiry",
                 "Deep OTM, far from expiry", "Deep ITM, near expiry"],
     "answer": 1, "topic": "Greeks",
     "exp": "Gamma peaks for ATM options and increases as expiry approaches."},
    {"q": "The maximum loss for the buyer of a call option is:",
     "options": ["Unlimited", "The strike price", "The premium paid", "Zero"],
     "answer": 2, "topic": "Options Basics",
     "exp": "A buyer can lose at most the premium paid."},
    {"q": "Selling a naked (uncovered) call option exposes the writer to:",
     "options": ["Limited risk", "No risk", "Unlimited risk",
                 "Risk capped at the premium"], "answer": 2,
     "topic": "Options Basics",
     "exp": "If the underlying rises without limit, a naked call's loss is "
            "theoretically unlimited."},
    {"q": "The intrinsic value of an out-of-the-money option is:",
     "options": ["Negative", "Zero", "Equal to the premium", "Equal to time value"],
     "answer": 1, "topic": "Options Basics",
     "exp": "OTM options have no intrinsic value; their price is all time value."},
    {"q": "A bull call spread is constructed by:",
     "options": ["Buying a higher-strike call, selling a lower-strike call",
                 "Buying a lower-strike call, selling a higher-strike call",
                 "Buying a call and a put at the same strike",
                 "Selling a call and a put at the same strike"], "answer": 1,
     "topic": "Strategies",
     "exp": "Buy the lower strike, sell the higher strike — a net debit spread."},
    {"q": "A long straddle is profitable when the underlying:",
     "options": ["Stays flat", "Moves sharply in either direction",
                 "Rises only", "Falls only"], "answer": 1, "topic": "Strategies",
     "exp": "Long straddle (buy ATM call + put) profits from a large move "
            "either way."},
    {"q": "An iron condor is a:",
     "options": ["Single-leg directional trade",
                 "Defined-risk, range-bound (short volatility) strategy",
                 "Unlimited-risk strategy", "Pure arbitrage"], "answer": 1,
     "topic": "Strategies",
     "exp": "It sells an OTM call spread and an OTM put spread — limited risk, "
            "profits if price stays in a range."},
    {"q": "Put-call parity states that C − P equals:",
     "options": ["S + PV(K)", "S − PV(K)", "PV(K) − S", "K − S"], "answer": 1,
     "topic": "Pricing",
     "exp": "C − P = S − K·e^(−rT) = S − PV(K) for European options."},
    {"q": "Implied volatility is best described as:",
     "options": ["Past realized volatility",
                 "The volatility implied by an option's market price",
                 "A fixed exchange-set value", "The risk-free rate"], "answer": 1,
     "topic": "Pricing",
     "exp": "IV is backed out of the market price using an option pricing model."},
    {"q": "The Black-Scholes model assumes the underlying price follows a:",
     "options": ["Normal distribution of prices",
                 "Lognormal distribution of prices",
                 "Uniform distribution", "Poisson process"], "answer": 1,
     "topic": "Pricing",
     "exp": "BS assumes lognormally distributed prices (normally distributed "
            "log returns) with constant volatility."},
    {"q": "Open interest represents:",
     "options": ["Total volume traded today",
                 "Total outstanding (open) contracts",
                 "Number of trades", "Exchange turnover"], "answer": 1,
     "topic": "Market Structure",
     "exp": "OI is the count of contracts that remain open, not yet squared off."},
    {"q": "When a futures contract trades above the spot price, the market is in:",
     "options": ["Backwardation", "Contango", "Inversion", "Settlement"],
     "answer": 1, "topic": "Futures",
     "exp": "Futures > spot is contango; futures < spot is backwardation."},
    {"q": "SPAN margin in F&O is computed based on:",
     "options": ["A flat percentage of turnover",
                 "Portfolio risk under a range of price/volatility scenarios",
                 "The broker's discretion", "Only the premium value"], "answer": 1,
     "topic": "Risk", "exp": "SPAN simulates portfolio P&L across scenarios to "
     "size the margin."},
    {"q": "India's default rolling settlement cycle for equities (since 2023) is:",
     "options": ["T+3", "T+2", "T+1", "T+5"], "answer": 2,
     "topic": "Market Structure",
     "exp": "Indian equities moved fully to a T+1 settlement cycle in 2023."},
    {"q": "Beta measures a stock's:",
     "options": ["Total risk", "Sensitivity of returns to the market",
                 "Dividend yield", "Liquidity"], "answer": 1, "topic": "Research",
     "exp": "Beta is systematic risk — co-movement with the market portfolio."},
    {"q": "Diversification primarily reduces:",
     "options": ["Systematic risk", "Market risk", "Unsystematic (specific) risk",
                 "Interest-rate risk"], "answer": 2, "topic": "Research",
     "exp": "Diversification cuts firm-specific risk; systematic risk remains."},
    {"q": "The P/E ratio is calculated as:",
     "options": ["Price ÷ earnings per share", "Earnings ÷ price",
                 "Price ÷ book value", "Dividend ÷ price"], "answer": 0,
     "topic": "Research", "exp": "P/E = market price per share ÷ EPS."},
    {"q": "In a dividend discount model (DDM), a stock's value equals:",
     "options": ["The sum of past dividends",
                 "The present value of expected future dividends",
                 "Book value plus reserves", "EPS times a fixed multiple"],
     "answer": 1, "topic": "Valuation",
     "exp": "DDM discounts expected future dividends to present value."},
    {"q": "Free cash flow to the firm (FCFF) is discounted using:",
     "options": ["Cost of equity", "WACC", "Risk-free rate", "Dividend yield"],
     "answer": 1, "topic": "Valuation",
     "exp": "FCFF (available to all capital providers) is discounted at WACC."},
    {"q": "The Sharpe ratio measures:",
     "options": ["Return per unit of systematic risk",
                 "Excess return per unit of total risk (standard deviation)",
                 "Return per unit of downside risk", "Absolute return"],
     "answer": 1, "topic": "Research",
     "exp": "Sharpe = (return − risk-free) ÷ standard deviation of returns."},
    {"q": "An RSI reading above 70 is conventionally interpreted as:",
     "options": ["Oversold", "Overbought", "Neutral", "A buy signal"], "answer": 1,
     "topic": "Technical",
     "exp": "RSI > 70 suggests overbought; RSI < 30 suggests oversold."},
    {"q": "Research analysts in India are regulated under regulations framed by:",
     "options": ["RBI", "IRDAI", "SEBI", "PFRDA"], "answer": 2, "topic": "Regulation",
     "exp": "SEBI (Research Analysts) Regulations, 2014 govern RAs in India."},
    {"q": "A bond's price and its yield to maturity move:",
     "options": ["In the same direction", "Inversely", "Independently",
                 "Only with coupons"], "answer": 1, "topic": "Fixed Income",
     "exp": "Higher yields imply lower prices and vice versa."},
    {"q": "A commonly used proxy for the risk-free rate in India is the:",
     "options": ["Corporate bond yield", "Government security (G-Sec) yield",
                 "Bank fixed-deposit rate", "Repo spread"], "answer": 1,
     "topic": "Valuation",
     "exp": "Sovereign G-Sec yields are the usual risk-free proxy."},
]
